# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:5.6.30-apache
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: /var/www/html

    steps:      
      - run: 
         name: permisos
         command: sudo chown -R circleci:circleci /var/www/html
        
      - checkout
      
      - run:
         name: instalar curl
         command: sudo apt-get install curl
        
      - run: 
         name: descargar getcomposer
         command: sudo php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
       
      - run:
         name: Instalar composer
         command: sudo php composer-setup.php
         
      - run:
         name: Instalar dependencias
         command: /var/html/composer.phar install --no-interaction
      
      - run:
         name: ls
         command: |
         ls
         v1/vendor/bin/phpunit -- bootstrap Model/Usuarios.php --testdox Tests
